### ISSUE TITLE
Increase testing coverage

### ISSUE THREAD

**Issue by mkeoliya** [AY2021S1-CS2103-T16-3/tp#173]
We should aim to hit 80% test coverage, with no long methods (>30 LoC) or nestings. 

As such, we should be adding tests to any and every file with less than 75% coverage (rationale: AB3 had a coverage of 72%).  Assigned are the files that each of us need to add tests for - i have assigned a file only if the teammate is the author with the last significant modification to the file(s). Can we aim to finish this by tomorrow night?

@JingYenLoh 
- `Semester` model
- `Tag` (optional)

@jetnew 
- `Allocation` model

@Lysire 
- `CreateEditCopy` test

@chloelee767 
- `AddRoomCommandParser`
-  `DeleteRoomCommandParser`
- `ListStudentsCommandParser`
- `EditRoomCommandParser` (also move it out of the `logic/parsers/exceptions` package)
- `AddRoomCommand`
- `DeleteRoomCommand`
- `EditRoomCommand`
- `ListStudentsCommand`

@mkeoliya 
- `DeleteAliasCommandParser`
- `RestoreCommand`
- `SetBinExpiryCommand`

**Comment by jetnew** [comment]
Agreed.

**Comment by mkeoliya** [comment]
Closing, since we reached our required target of 72%.
