### ISSUE TITLE
Minor documentation bugs in UG

### ISSUE THREAD

**Issue by theodoreleebrant** [AY2021S1-CS2103-T16-3/tp#203]
Found these small nits in the UG:

Quick Start
1. <Change in to on>

`allocate / deallocate/ reallocate`
First bullet point: probably want to change students list to student list / students' list

`deallocate`
must be positive a integer 1, 2, 3, … 

`add-student`
The student ID must be an 8-digit...
The student will not be added if some pieces of information are missing. 

General
- Typo: recyling

`alias`
Henceforth, sb and set-bin-expiry command will have the same effect
(consider adding the before set-bin-expiry or just remove the word command)

`dealias`
dealias c/set-bin-expiry a/sb removes the an alias sb for the set-bin-expiry command. 

`toggle-split`
which is shown in the image below.

**Comment by Lysire** [comment]
Closed #203 via #204
