### ISSUE TITLE
UG: Add collapsible panels for negative examples of command usage

### ISSUE THREAD

**Issue by mkeoliya** [AY2021S1-CS2103-T16-3/tp#97]
Would entail this:

<details>
 <summary>Negative Examples (click to expand) </summary>
   - Negative Example 
</details>

```
<details>
<summary> Negative Examples (click to expand) </summary>
  - Negative Example 
</details>
```

Pros: Adds more detail to our UG 
Cons: Makes it easier to find bugs in UG.

**Comment by JingYenLoh** [comment]
I'm not sure if this is necessary. @mkeoliya what are your current thoughts on this?

**Comment by mkeoliya** [comment]
Yeah I agree - better to make it clear exactly when an error message is shown. Closing now.
